razorpay:
  key: rzp_test_S66nQ4PLAPLVqo
  secret: 31js6f8YlDfKpzq2Zdgg0y2z

server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://chakravaram24bcs10113_db_user:karthik123@cluster4.f0bqtlj.mongodb.net/razorpay_demo?retryWrites=true&w=majority